YouInvestMe/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YouInvestMe.Data;
using YouInvestMe.Models;

namespace YouInvestMe.Controllers
{
    // Requires the manager role to access anything related to this controller
    [Authorize(Roles = "Manager")]
    public class ClientController : Controller
    {
        private readonly ApplicationDbContext _context;

        // Imports context for CRUD operations with MySQL database
        public ClientController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Client
        // Returns all of the clients from the database table
        public async Task<IActionResult> Index()
        {
              return _context.Client != null ? 
                          View(await _context.Client.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Client'  is null.");
        }

        // GET: Client/Details/5
        // Returns a more detailed view of a selected client
        public async Task<IActionResult> Details(int? id)
        {
            // Shows an error if the client does not exist
            if (id == null || _context.Client == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.ClientId == id);
            if (client == null)
            {
                return NotFound();
            }

            var ideas = await _context.Idea.Where(u => u.Clients.Any(i => i.ClientId == id)).ToListAsync();
            ViewBag.Ideas = ideas;
            return View(client);
        }

        // GET: Client/Create
        // Returns the Client/Create view
        public IActionResult Create()
        {
            ViewData["RiskLevelId"] = new SelectList(_context.RiskLevel, "RiskLevelId", "RiskLevelId");
            return View();
        }

        // POST: Client/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientId,Name,Description,Region,RiskLevelId")] Client client)
        {
            // Checks if the inputted values fit the Client Model
            if (ModelState.IsValid)
            {
                // Adds a new client to the database
                _context.Add(client);
                await _context.SaveChangesAsync();
                // Returns the user to /Client/Index
                return RedirectToAction(nameof(Index));
            }
            ViewData["RiskLevelId"] = new SelectList(_context.RiskLevel, "RiskLevelId", "RiskLevelId", client.RiskLevelId);
            return View(client);
        }

        // GET: Client/Edit/5
        // Returns the view for /Client/Edit/{id}
        public async Task<IActionResult> Edit(int? id)
        {
            // Shows an error if the client does not exist
            if (id == null || _context.Client == null)
            {
                return NotFound();
            }

            var client = await _context.Client.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            ViewData["RiskLevelId"] = new SelectList(_context.RiskLevel, "RiskLevelId", "RiskLevelId", client.RiskLevelId);
            return View(client);
        }

        // POST: Client/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // Takes the values inputted and edits the client
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClientId,Name,Description,Region,RiskLevelId")] Client client)
        {
            // If the selected id does not match the ClientId return error
            if (id != client.ClientId)
            {
                return NotFound();
            }

            // Checks if the inputted data fits the client model
            if (ModelState.IsValid)
            {
                try
                {
                    // Attempt to update the client info
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    // Return error if edit tries to change the id to one that already exists
                    if (!ClientExists(client.ClientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RiskLevelId"] = new SelectList(_context.RiskLevel, "RiskLevelId", "RiskLevelId", client.RiskLevelId);
            return View(client);
        }

        // GET: Client/Delete/5
        // Controller to delete a client from the database
        public async Task<IActionResult> Delete(int? id)
        {
            // Return error if selected client does not exist
            if (id == null || _context.Client == null)
            {
                return NotFound();
            }

            // Checks if the client instance is not fully null
            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.ClientId == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Client/Delete/5
        // Controller to complete deletion action
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Checks if client is null and returns error if so
            if (_context.Client == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Client' is null.");
            }
            // Deletes the selected client
            var client = await _context.Client.FindAsync(id);
            if (client != null)
            {
                _context.Client.Remove(client);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // Used in edit controller to confirm of the client exists
        private bool ClientExists(int id)
        {
          return (_context.Client?.Any(e => e.ClientId == id)).GetValueOrDefault();
        }
    }
}

YouInvestMe/Controllers/IdeaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using YouInvestMe.Data;
using YouInvestMe.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace YouInvestMe.Controllers
{
    [Authorize]
    public class IdeaController : Controller
    {
        private readonly ApplicationDbContext _context;

        // Create context for CRUD operations with MySQL database
        public IdeaController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: Idea    
        // Return all ideas from database

        // However, if there is a certain search string,
        // return only matches against title from database
        public async Task<IActionResult> Index(string searchString)
        {

            if (_context.Idea == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Idea'  is null.");
            }
            var ideas = from i in _context.Idea
                        select i;

            if (!String.IsNullOrEmpty(searchString))
            {
                ideas = ideas.Where(s => s.Title!.Contains(searchString));
            }

            return View(await ideas.OrderByDescending(x => x.PublishedDate).ToListAsync());
        }


        // GET: Idea/Details/5
        // Expanded version of the idea record in the database
        // Returns 404 Not Found if the record does not exist

        // Gets the {id} from the route in URL
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Idea == null)
            {
                return NotFound();
            }

            var idea = await _context.Idea
                .FirstOrDefaultAsync(m => m.IdeaId == id);
            if (idea == null)
            {
                return NotFound();
            }

            return View(idea);
        }

        // GET: Idea/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Idea/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdeaId,Title,Abstract,PublishedDate,ExpiriesDate,ProductType,Instruments,Currency,Region,Country,UserID")] Idea idea)
        {
            // Check if the Model state is valid
            if (ModelState.IsValid)
            {
                // Set published date attribute to current date today.
                idea.PublishedDate = DateTime.Now;

                // Identify who created the idea and set it as UserID
                idea.UserID = User.Identity.Name;

                // Add record to the database
                _context.Add(idea);
                // Maps to SQL query as: "INSERT INTO Ideas (...) VALUES (...)"
                // (...) is what comes in the arguments of this function

                // Asynchronously save changes to the database
                await _context.SaveChangesAsync();

                // Return to the index page of all ideas
                return RedirectToAction(nameof(Index));
            }
            return View(idea);
        }

        // GET: Idea/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Idea == null)
            {
                return NotFound();
            }

            var idea = await _context.Idea.FindAsync(id);
            if (idea == null)
            {
                return NotFound();
            }
            return View(idea);
        }

        [Authorize(Roles = "Manager")] // Only managers can assign Client to the idea
        public async Task<IActionResult> Assign(int? id)
        {
            if (id == null || _context.Idea == null)
            {
                return NotFound();
            }

            var idea = await _context.Client.ToListAsync();
            if (idea == null)
            {
                return NotFound();
            }
            return View(idea);
        }

        // POST: Idea/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdeaId,Title,Abstract,ExpiriesDate,ProductType,Instruments,Currency,Region,Country")] Idea idea)
        {
            // If there is no idea to edit, return 404 Not Found
            if (id != idea.IdeaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Update the database with new records
                    _context.Update(idea);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IdeaExists(idea.IdeaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                // Return Index view at the end
                return RedirectToAction(nameof(Index));
            }
            return View(idea);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        // Validating roles and http-form-post attacks (brute force, DoS)
        public async Task<IActionResult> Assign(int id, int clientid, ClientIdea ct)
        {
            if (ModelState.IsValid)
            {
                ct.IdeaId = id;
                ct.ClientId = clientid;

                // TODO: Prevent from assigning the same client to the idea TWICE

                // var matching = _context.ClientIdea.Where(x => x == ct).ToListAsync();
                // if (matching == null)
                // {

                // Assign client to the current idea
                _context.ClientIdea.Add(ct);
                await _context.SaveChangesAsync();
                // }

                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Idea/Delete/5
        // Returns to confirmation view that the idea with id given in the /{id} part of the URL
        // is going to be deleted.
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Idea == null)
            {
                return NotFound();
            }

            var idea = await _context.Idea
                .FirstOrDefaultAsync(m => m.IdeaId == id);
            if (idea == null)
            {
                return NotFound();
            }

            return View(idea);
        }

        // POST: Idea/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Idea == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Idea'  is null.");
            }
            var idea = await _context.Idea.FindAsync(id);
            if (idea != null)
            {
                // Delete operation with Entity Framework
                // Binds to SQL query -> DELETE FROM Ideas WHERE IdeaId = id; 
                _context.Idea.Remove(idea);
            }

            // Update the database with new changes
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // Helper function that checks whether the idea with the given id exists or not
        // Return type `bool`
        private bool IdeaExists(int id)
        {
            return (_context.Idea?.Any(e => e.IdeaId == id)).GetValueOrDefault();
        }
    }
}

YouInvestMe/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
    
@{
    string userrole = "";
}

@foreach (var claim in User.Claims)
{
    if (claim.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/role")
    {
        userrole = claim.Value;
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YouInvestMe</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/yeti.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/YouInvestMe.styles.css" asp-append-version="true" />
</head>
<body>
    @if (SignInManager.IsSignedIn(User)){
        
    @* App Layout *@
    <div class="vh-100 w-100 d-flex flex-column flex-nowrap">
        
        @* Header *@
        <header class="flex-shrink-0">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-secondary border-bottom box-shadow flex-shrink-0">
                <div class="container-fluid">  
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/assets/logo.svg" class="me-2" width='32' height='32' alt="Logo" />YouInvestMe</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1 ms-4 my-2">
                            <li class="nav-item border-start my-1 border-primary px-2 ">
                                <a class="nav-link text-dark link-primary" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item my-1 border-primary px-2 ">
                                <a class="nav-link text-dark link-primary" asp-area="" asp-controller="Idea" asp-action="Index">Ideas</a>
                            </li>
                            @if (userrole == "Manager") {
                            <li class="nav-item my-1 border-primary px-2 ">
                                <a class="nav-link text-dark link-primary" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item my-1 border-primary px-2 ">
                                <a class="nav-link text-dark link-primary" asp-area="" asp-controller="Client" asp-action="Index">Clients</a>
                            </li>
                            }                
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </header>
        
        @* Main body *@
        <div class="px-5 pt-3 pb-5 overflow-auto flex-grow-1">
            <main role="main">
                @RenderBody()
            </main>
        </div>
        
        @* Footer *@
        <footer class="border-top flex-shrink-0 d-flex flex-column justify-content-center bg-white text-muted" style="height: 70px;">
            <div class="d-flex justify-content-between w-75 mx-auto"> 
                <div class="text-center">
                    &copy; 2022 - YouInvestMe
                </div>
                <div class=''>
                    <a href="https://github.com/nuriddinislamov/YouInvestMe" target='_blank' class="mx-2 text-decoration-none">GitHub</a>
                    <a asp-controller="Home" asp-action="Contact" class="mx-2 text-decoration-none">Contact Us</a>
                    <a href="https://www.aru.ac.uk/" target="_blank" class="mx-2 text-decoration-none">ARU</a>
                </div>
            </div>
        </footer>
    </div>
    } else {
        <div class="container">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    }
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>